

txt_usr = "Xpath://input[@id='username']"
txt_pws = "Xpath://input[@id='password']"
click_patient_ward = "id:Inpatient Ward"
click_login = "xpath://input[@id='loginButton']"
link_Register_a_Patient = "id:referenceapplication-registrationapp-registerPatient-homepageLink-referenceapplication-registrationapp-registerPatient-homepageLink-extension"
txt_given = "xpath:/html[1]/body[1]/div[1]/div[3]/form[1]/section[1]/div[1]/fieldset[1]/div[1]/p[1]/input[1]"
txt_family = "xpath:/html[1]/body[1]/div[1]/div[3]/form[1]/section[1]/div[1]/fieldset[1]/div[1]/p[3]/input[1]"
btn_nxt = "xpath://button[@id='next-button']"
day = "xpath://input[@id='birthdateDay-field']"
year = "xpath://input[@id='birthdateYear-field']"
txt_addr = "xpath://input[@id='address1']"
txt_addr2 = "xpath://input[@name='address2']"
txt_city = "xpath://input[@name='cityVillage']"
txt_state = "xpath://input[@name='stateProvince']"
country = "xpath://input[@name='country']"
ph_no = "xpath:/html[1]/body[1]/div[1]/div[3]/form[1]/section[2]/div[1]/fieldset[2]/p[1]/input[1]"
p_code = "xpath://input[@name='postalCode']"
p_name = "xpath://body/div[@id='body-wrapper']/div[@id='content']/form[@id='registration']/section[@id='relationships-info']/div[1]/fieldset[1]/div[1]/div[1]/p[2]/input[1]"
confirm = "xpath:/html[1]/body[1]/div[1]/div[3]/form[1]/div[1]/div[5]/p[1]/input[1]"
m_page = "xpath://a[normalize-space()='']"
click_patient_record = "xpath:coreapps-activeVisitsHomepageLink-coreapps-activeVisitsHomepageLink-extension"